Propose Project 6
SwiftFMI/iOS_2024_2025 pull request #1
Opened 2024-12-16 21:40 UTC by marktitorenkov

2024-12-19 10:38 UTC, heitara requested changes

2024-12-19 10:38 UTC, heitara commented on projects/list/prj6.md
> +    - Жанрове (напр. комедии, драми, трилъри)
От къде ще идват взъможните жанрове?
Ще има ли локализация на интерфейса?

2024-12-19 10:38 UTC, heitara commented on projects/list/prj6.md
> +* **API за филмови бази данни**
Може ли да се добавят и платформите, където са достъпни филмите, като netflix и подобни.

2024-12-19 11:39 UTC, marktitorenkov commented on projects/list/prj6.md
> +    - Жанрове (напр. комедии, драми, трилъри)
В API-то на TMBD има [endpoint](https://developer.themoviedb.org/reference/genre-movie-list), който връща списък от възможните филмови жанрове (около 20).

Цялото API е локализирано, включително имената на жанрове, филми, актьори, и т.н. Базата се попълва от доброволци, но за повечето известни филмови заглавия има български превод.

Това значи, че може да се локализира и нашият UI.

2024-12-19 11:39 UTC, marktitorenkov commented on projects/list/prj6.md
> +* **API за филмови бази данни**
Да, този [endpoint](https://developer.themoviedb.org/reference/movie-watch-providers) предоставя информация в кои платформи може да се гледа даден филм.

Можем да добавим, при регистрация, избор на платформите, които потребителите ползват за да се ограничат предложенията само до тях.

2024-12-30 14:30 UTC, heitara approved these changes
Действаме!

2024-12-30 14:30 UTC, merged